
version: '3'
services:
  db:
    image: postgres:13  
    environment:
      POSTGRES_DB: Customer_Order
      POSTGRES_USER: dorcas_mutisya
      POSTGRES_PASSWORD: 1244
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 customers_orders_project.wsgi:application  # Used gunicorn
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # To tell Docker Compose to use the .env file
    environment:
      POSTGRES_DB: Customer_Order  # Added these for Django to connect to DB
      POSTGRES_USER: dorcas_mutisya
      POSTGRES_PASSWORD: 1244
      DB_HOST: db                   
      SECRET_KEY: ${SECRET_KEY}    # SECRET_KEY from .env

