apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001  # You can choose any available port
  selector:
    app: django-app
